### ISSUE TITLE
Add time series 

### ISSUE THREAD

**Issue by hhucyl** [langevin-usgs/mf6flopy2019_classrepo#1]
Hi
I am a new learner to flopy, I found that this repo is extremely helpful for new beginners like me. However, I would like to ask how to generate a time series file in Ex06 and Ex07, since you load them from the existing file. For example, if I want to input a time series of head and discharge in the river of ex02, what should I do? Sorry for I may have asked a stupid question here.
Cheers
Yilin

**Comment by christianlangevin** [comment]
There is an example here that should help: https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_mf6_B_complex-model.ipynb
